### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [iota9star/mikan_flutter#20]
请问我是否可以将此应用打包发布到 F-Droid？谢谢

**Comment by iota9star** [comment]
不会存在签名不一致的问题吗

**Comment by linsui** [comment]
存在，除非实现可重复构建。所以 F-Droid 的版本和其他版本不能相互更新。

**Comment by iota9star** [comment]
这个支持action吗，是否可以自动构建？

**Comment by linsui** [comment]
F-Droid 每天自动检查更新，从最新 Tag 构建新版本。构建在 F-Droid 的 buildserver 上完成，之后会离线签名，一般在上游更新后两三天内发布。

**Comment by iota9star** [comment]
有示例吗？可以快速集成的那种。现在最新版本是同步到play了的

**Comment by iota9star** [comment]
我看了一下F-Droid的[收录政策](https://f-droid.org/zh_Hans/docs/Inclusion_Policy/)，现在应用带有play service和firebase

**Comment by linsui** [comment]
我可以写个构建配方提交。一般可以通过 flavor 或者 patch 的方式去掉 gms 和 firebase，这个会比较麻烦。我不是 Android 开发者所以也帮不上忙。可以参照其他 Flutter 应用的构建配方。比如 https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/io.github.danxi_dev.dan_xi.yml

**Comment by iota9star** [comment]
这个没问题，后面可以排除，flutter端通过构建变量注入到flutter里面可以去掉firebase相关的。但实际情况还得看时间安排，后面我会进行尝试的

**Comment by linsui** [comment]
我试了一下把 firebase 去掉，但 apk 似乎连不上网。https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11159 报错 dns 解析失败。

**Comment by linsui** [comment]
@lycstar 请问为什么关掉 issue？
