### ISSUE TITLE
极为惊艳的App，看到源码中有macOS工程，请问要如何构建成App

### ISSUE THREAD

**Issue by blacklein** [iota9star/mikan_flutter#23]
极为惊艳的App，配合下载工具非常方便，观感也非常棒，一开始还以为是官方app，感谢大佬！

看到源码中有macOS工程，请问要如何构建成App，用fastlane和xcodebuild命令构建失败了，用xcode构建报错不知道如何解决，请大佬教一下，谢谢！

**Comment by iota9star** [comment]
可以提供一下报错信息，我是直接pod install之后就可以跑了

**Comment by blacklein** [comment]
桌面有个fluent reader好像是flutter的，但打包用的是electron，作者或许可以参考下思路

**Comment by iota9star** [comment]
你这么说就尴尬了，flutter为啥要用electron，在我看来electron这个只是一种很糟糕的实现，完全不具备一个应用该有的样子，只是方便前端开发也能接入桌面开发而已。当然，flutter现在也只是勉强够用，还是很卡。

上面提到的搞坏了只是因为有个库出问题了，顶部的控制显示有问题，也不是啥大问题，之前修了没空测试

**Comment by blacklein** [comment]
有用tauri代替electron的趋势，但在别的仓库看到有作者说tauri性能上是比较有优势，但完善度还是不及electron，有些前端问题无法解决，话又说回来，之前看到新闻，github自己好像都打算放弃electron了，只是说作为前端跨平台实现，我个人觉得electron是个比较容易的方案，当然能有原生switft、原生flutter跨平台跨架构应用自然更好，奈何好多优秀的仓库都是单平台的，左右四顾也就electron似乎还算一个比较普适的前端实现方案，徒呼奈何

**Comment by iota9star** [comment]
已可以从 [release](https://github.com/iota9star/mikan_flutter/releases)  下载
