### ISSUE TITLE
请问如何自行build macos app？

### ISSUE THREAD

**Issue by blacklein** [iota9star/mikan_flutter#24]
是否可以提供详细步骤，谢谢！

**Comment by iota9star** [comment]
直接在mac上进入项目目录，执行flutter pub get 然后再执行flutter build macos --release就可以了，试试？

**Comment by iota9star** [comment]
前提是有flutter环境和xcode环境

**Comment by iota9star** [comment]
你这没报错啊？你看看build目录有了吗

**Comment by iota9star** [comment]
release里面有build好的，可以直接用

**Comment by blacklein** [comment]
在build里面找到了
但是现实是apple silicon和intel兼容的“通用”版
我想本地build是想要只有apple silicon的版本
我自己测试其他开源项目时发现，不知道是苹果自己的问题还是别的原因，单apple芯片的版本反而速度比通用的速度快，通用的总是慢半拍

**Comment by blacklein** [comment]
是否有办法指定build的arch？

**Comment by iota9star** [comment]
打开xcode删除target应该就行了，再build settling里面

**Comment by iota9star** [comment]
你看看build setting里面有没有architecture关键字的，改成你要的架构应该就ok了

**Comment by blacklein** [comment]
```
# Clone repo
git clone --recurse-submodules https://github.com/iota9star/mikan_flutter.git

# Open Runner.xcodeproj in Xcode
# Building Setting - Build Active Architecture Only - Set option to Yes
flutter build macos --release
```
解决了，已构建成功单独arm64架构的app，比universal在m1 mac上要顺畅一些，启动秒开
