### ISSUE TITLE
字体希望添加更纱黑体的选项

### ISSUE THREAD

**Issue by zbodo** [iota9star/mikan_flutter#26]
如题，[更纱黑体](https://github.com/be5invis/Sarasa-Gothic)是一个非常棒的开源字体项目，期待能添加入字体列表

**Comment by iota9star** [comment]
之前丢在jsdeliver上面的，现在国内屏蔽了，就没再加字体了，字体是放在 [fonts](https://github.com/iota9star/fonts) 这个仓库里面的

**Comment by iota9star** [comment]
已添加
