### ISSUE TITLE
自适应图标支持请求

### ISSUE THREAD

**Issue by SuuKomura** [iota9star/mikan_flutter#3]
如题，作为原生用户处境日常艰难……

**Comment by iota9star** [comment]
试试v0.0.19版本呢

**Comment by SuuKomura** [comment]
> 试试v0.0.19版本呢
非常完美，感谢。
另外有个挺私人的feature请求：能否支援英文呢？哪怕只有应用名也好。因为是挺任性的需求所以如果非常麻烦就不需要做了，再次感谢。
