### ISSUE TITLE
希望优化冷启动速度

### ISSUE THREAD

**Issue by newSF** [iota9star/mikan_flutter#33]
冷启动速度7秒左右。
![SC-1679634896754.gif](https://user-images.githubusercontent.com/128767067/227430608-bc300367-392f-47f3-b4c0-accc762562e4.gif)

**Comment by iota9star** [comment]
中间icon可以点的，可以马上进入

**Comment by iota9star** [comment]
现在添加直观的文字提示，点击即可进入首页
