### ISSUE TITLE
更换网站解析域名

### ISSUE THREAD

**Issue by PIut02** [iota9star/mikan_flutter#36]
原域名mikanani.me在大陆地区已无法正常访问，请求更换最新网站域名mikanime.tv

**Comment by iota9star** [comment]
还没改完，新版本还在测试CI![1683825936789.jpg](https://github.com/iota9star/mikan_flutter/assets/21272154/d522cd31-1155-4cdd-83c5-28df961bc4bc)

**Comment by PIut02** [comment]
我看没人回还以为已经完成了（

**Comment by iota9star** [comment]
1.1.0打出来功能是有了，可以下载试试，不过还不知道有没有问题，明天再看了，有什么建议或者bug，可以提

**Comment by PIut02** [comment]
试了下网络问题已经解决了，关于ui方面，既然都采用md3设计了能否直接使用md3的动态取色，底部手势提示线能沉浸的话就更好了，不知道实现起来有没有难度

**Comment by iota9star** [comment]
新的需求开新的issue，导航栏沉浸之前应该是api改了，现在重新调整好了。等1.1.2打包完就可以支持了
