### ISSUE TITLE
iOS版无法加载任何图片

### ISSUE THREAD

**Issue by zxc929961112** [iota9star/mikan_flutter#42]
使用AltStore侧载安装Mikan_Flutter，然而打开后无法加载图片!尝试过网页是一切正常的，换节点也无效
[image](https://github.com/iota9star/mikan_flutter/assets/32637692/1c7cfb66-7353-4320-9f03-82ef899eaf6e)![image](https://github.com/iota9star/mikan_flutter/assets/32637692/c98688bf-58fb-402a-8532-7176656f1762)![image](https://github.com/iota9star/mikan_flutter/assets/32637692/7ff798fb-be72-4b78-8365-e6dc313f73a6)![image](https://github.com/iota9star/mikan_flutter/assets/32637692/976ba7f4-478c-4325-97b4-a9588372b1a7)

**Comment by iota9star** [comment]
我这里是正常的，请检查是否关闭代理，并且使用国内镜像地址。当然你也可以使用代理，使用原始地址。
关键点：
1. 使用国内镜像，ip需在国内
2. 原始地址，ip需在国外

**Comment by zxc929961112** [comment]
谢谢，我添加了两条规则后好了，现在用了国内镜像。那么我想问一下如何让mikan flutter使用原始地址呢？没有找到相关按钮

**Comment by zxc929961112** [comment]
我找到了，谢谢你的答复！
