### ISSUE TITLE
问题:订阅x字幕组的x番时，直接订阅所有x番番下的所有字幕组

### ISSUE THREAD

**Issue by scdyysf** [iota9star/mikan_flutter#43]
例如:
我没有订阅死神
![Screenshot_2023-07-23-20-39-47-979_com.microsoft.emmx.jpg](https://github.com/iota9star/mikan_flutter/assets/111550659/2204c1b2-65cb-4366-8df0-fb0d447f70cf)

在APP里订阅ANI死神的源![Screenshot_2023-07-23-20-41-54-547_io.nichijou.flutter.mikan.jpg](https://github.com/iota9star/mikan_flutter/assets/111550659/55c40c1f-4de6-46a1-97f0-a5a91c204e0e)

![Screenshot_2023-07-23-20-42-59-093_io.nichijou.flutter.mikan.jpg](https://github.com/iota9star/mikan_flutter/assets/111550659/ede797d1-017b-404e-86e2-bc80379876a8)

在网页端发现直接订阅了死神下面的所有字幕组的源![Screenshot_2023-07-23-20-43-23-956_com.microsoft.emmx.jpg](https://github.com/iota9star/mikan_flutter/assets/111550659/db4a3695-db7d-4bd3-ba7e-df852a6f91e3)

不清楚这个算不算是bug，主要只是想在app里面订阅某一个字幕组的某一部番不知道怎么操作

**Comment by iota9star** [comment]
APP暂不支持单独订阅某个字幕组，意义不大，查看详情和订阅列表实际内容少，如果字幕组断更就没有了，所以APP没有实现，也不会去实现，这个是登录账号的一个设置

**Comment by scdyysf** [comment]
> APP暂不支持单独订阅某个字幕组，意义不大，查看详情和订阅列表实际内容少，如果字幕组断更就没有了，所以APP没有实现，也不会去实现，这个是登录账号的一个设置

好的，感谢大佬回答

**Comment by bearcloney** [comment]
> APP暂时不支持单独订阅某个字幕组，意义不大，查看详情和订阅列表实际内容少，如果字幕断组更就没有了，所以APP没有实现，也不会去实现，这是登录账号的一个设置

大佬你好，我认为这个功能还是很重要的，首先我的nas没那么大空间下这么多版本
这么多版本对emby挂削也不便
而baha源的字幕组一般不会断更，所以我也基本不会遇到这种问题
虽然对你可能不怎么重要，但我真的很需要他

**Comment by iota9star** [comment]
只是需要复制一下订阅源的地址吗

**Comment by iota9star** [comment]
已添加

**Comment by scdyysf** [comment]
> 已添加

感谢大佬🙏

**Comment by scdyysf** [comment]
> 已添加

更新了一下，试了一下，可能是我的表达有误，我希望实现的功能是，在app中点击一个番，里面有多个字幕组，点击“**某个图标**”选择添加其中一个字幕组的rss订阅源。
比如在如图所示的地方添加一个❤按钮，![Screenshot_2023-08-20-01-34-15-726_io.nichijou.flutter.mikan-edit.jpg](https://github.com/iota9star/mikan_flutter/assets/111550659/604618e4-d09b-4adc-b048-b03784bfb621)

点击后就可以只添加死神里面ani字幕组的源。
类似于网页端的这个按钮。
![Screenshot_2023-08-20-01-37-14-151_com.microsoft.emmx-edit.jpg](https://github.com/iota9star/mikan_flutter/assets/111550659/9005fc05-0021-4611-9467-95306158aa30)

主要是对于我app基本上能实现大多数功能，比网页端要更方便，但因为不能单独添加x字幕组的x番，所以还是是不是会使用网页版，比麻烦希望大佬考虑一下能不能添加，感谢🙏。

补充说明一下因为我订阅rss源是订阅的网站首页的个人rss源（包含了自己加了心的所有番剧），所以新加的这个每个字幕组单独一个rss源对我并不试用，我在网站上的操作是有想看的番，就选择其中一个字幕组，点击❤添加订阅，但是还是很感谢大佬写了这个功能。

**Comment by iota9star** [comment]
上面字幕组有这个按钮![Screenshot_2023-08-20-01-25-08-65_8b62dbcb4bfbe8ae73aec6962b291ed6.jpg](https://github.com/iota9star/mikan_flutter/assets/21272154/3ed8429f-8cc4-438b-aeed-db984321201f)

![Screenshot_2023-08-20-01-25-16-77_8b62dbcb4bfbe8ae73aec6962b291ed6.jpg](https://github.com/iota9star/mikan_flutter/assets/21272154/83e9ee5d-84a6-4c7e-a6bc-50947597a8e9)

这个可以满足吗

**Comment by scdyysf** [comment]
> 上面字幕组有这个按钮![Screenshot_2023-08-20-01-25-08-65_8b62dbcb4bfbe8ae73aec6962b291ed6.jpg](https://github.com/iota9star/mikan_flutter/assets/21272154/3ed8429f-8cc4-438b-aeed-db984321201f)
> 
> ![Screenshot_2023-08-20-01-25-16-77_8b62dbcb4bfbe8ae73aec6962b291ed6.jpg](https://github.com/iota9star/mikan_flutter/assets/21272154/83e9ee5d-84a6-4c7e-a6bc-50947597a8e9)
> 
> 这个可以满足吗

哦抱歉，因为没有说明文档和更新说明，所以没有注意到，这个按钮可以满足我所有的需求，感谢大佬🙏，就是不知道其他人能看出这个功能不😂

**Comment by iota9star** [comment]
每个字幕组单独一个按钮，实现起来简单，如果是网页还好，手机端交互起来太麻烦了，现在只给了一个单独的入口

**Comment by scdyysf** [comment]
> 每个字幕组单独一个按钮，实现起来简单，如果是网页还好，手机端交互起来太麻烦了，现在只给了一个单独的入口

好的，对我来说，现在这个就挺好的，比我之前预想的实现方法要好，现在我觉得可能有点问题的是这个按钮有点太不起眼了，其他人可能注意不到。当然我在你的提醒下已经知道怎么操作了![Screenshot_2023-08-20-02-12-15-849_io.nichijou.flutter.mikan-edit.jpg](https://github.com/iota9star/mikan_flutter/assets/111550659/ec5a2cfd-765b-4a2a-ae48-8ae8480eb73d)

**Comment by scdyysf** [comment]
> 每个字幕组单独一个按钮，实现起来简单，如果是网页还好，手机端交互起来太麻烦了，现在只给了一个单独的入口
交互麻烦是指操作不方便吗？我想了想，能不能把添加方式改成长按此处的字幕组图标，可能会方便一些？，当然这样的话可能想像新功能里面单独选择简中和繁中就不是太好实现。![Screenshot_2023-08-20-02-19-14-450_io.nichijou.flutter.mikan-edit.jpg](https://github.com/iota9star/mikan_flutter/assets/111550659/939e8571-7309-4a5b-ad3e-2d057dba10b8)

**Comment by iota9star** [comment]
正常设计是图标按钮的，现在为了明显实际都换成带背景的按钮了，不过不太关键。打开页面没注意到的话，那没救了。只能加个文案了

**Comment by scdyysf** [comment]
> 正常设计是图标按钮的，现在为了明显实际都换成带背景的按钮了，不过不太关键。打开页面没注意到的话，那没救了。只能加个文案了

好的谢谢大佬
