### ISSUE TITLE
无图标和求Rss

### ISSUE THREAD

**Issue by ametoyuki098** [iota9star/mikan_flutter#44]
安装过后桌面显示一个绿色图标，能正常使用。是否和我手机安卓版本的关系。还有就是能否加入rss订阅这个功能，因为我看到mikan要获取rss只能去电脑上，所以开发者是否可以在这个客户端上加入获取的可能。谢谢🙏

**Comment by iota9star** [comment]
RSS的作用是什么？现在有应用内订阅，加RSS还没有现有订阅好用

**Comment by lilynas** [comment]
> RSS的作用是什么？现在有应用内订阅，加RSS用处不大，是需要其它功能吗

主要是给qbittorrent|download station|utorrent之类的支持RSS订阅的下载工具用的，搭配NAS的话很方便

**Comment by iota9star** [comment]
> <img alt="@lilynas" width="40" height="40" src="https://avatars.githubusercontent.com/u/31757534?s=80&amp;u=b19d43cd49a85944898af2d50e050b58dd33ff0d&amp;v=4">
这个订阅直接复制订阅地址就好了啊？能直接告诉我怎么用吗

**Comment by lilynas** [comment]
> > <img alt="@lilynas" width="40" height="40" src="https://avatars.githubusercontent.com/u/31757534?s=80&amp;u=b19d43cd49a85944898af2d50e050b58dd33ff0d&amp;v=4">
> 
> 这个订阅直接复制订阅地址就好了啊？能直接告诉我怎么用吗

目前我主要是搭配这个项目使用：[iota9star/mikan_flutter](https://github.com/iota9star/mikan_flutter)
蜜柑的订阅可以参看下这个项目的文档：[准备 Mikan RSS 订阅链接](https://www.autobangumi.org/config/rss.html)

**Comment by iota9star** [comment]
已添加
