### ISSUE TITLE
希望能增加《霞鹜新晰黑》《MiSans》和《句读黑体 UI》

### ISSUE THREAD

**Issue by howlingFounts** [iota9star/mikan_flutter#45]
看到这个 App 有“字体管理”功能，非常惊喜，感谢开发者的付出！
希望能增加《[霞鹜新晰黑](https://github.com/lxgw/LxgwNeoXiHei)》《[MiSans](https://web.vip.miui.com/page/info/mio/mio/detail?postId=33935854)》和《[句读黑体 UI](https://github.com/JudouEco/JudouSans/releases/download/v1.26/judou-sans-ui-hans-ttf-unhinted-1.26.zip)》。
**多谢！**

**Comment by iota9star** [comment]
字体在这儿 [iota9star/fonts](https://github.com/iota9star/fonts)，如果可以PR的话，欢迎添加。最近没有啥空，只能做一些简单的东西
