### ISSUE TITLE
是否考虑更新「霞鹜文楷」字体？

### ISSUE THREAD

**Issue by lxgw** [iota9star/mikan_flutter#46]
首先，感谢贵软件开发者的付出以及对「霞鹜文楷」字体的认可。

只是，版本有点旧了。与这款软件内置的版本相比，新版字体的「组」「剑」等字形有了一定的优化。

![MuMu12-20230821-091724](https://github.com/iota9star/mikan_flutter/assets/51902309/221f29d4-f11b-4554-9cff-2486bc2230b9)
![MuMu12-20230821-091850](https://github.com/iota9star/mikan_flutter/assets/51902309/9faac4d4-6f30-4b39-b5ed-1b95622934f0)

![image](https://github.com/iota9star/mikan_flutter/assets/51902309/8ac1f325-c98b-4386-aa20-2261849f211d)

（建议选用 [轻便版](https://github.com/lxgw/LxgwWenKai-Lite)，便于完整版相比剔除一些较不常用的字符，便于开发者将字体嵌入软件中。）

**Comment by iota9star** [comment]
先前没有考虑做版本管理，最近比较忙，后面有空才进行调整。字体管理的所有字体都是放这儿的 [fonts](https://github.com/iota9star/fonts)

**Comment by iota9star** [comment]
已更新 https://github.com/iota9star/fonts/pull/1
