### ISSUE TITLE
账号无法登录成功

### ISSUE THREAD

**Issue by TingTing1990** [iota9star/mikan_flutter#49]
最新版，登录后显示登录成功，但是好像没有效果，再次进入登录的界面没有显示账号

**Comment by iota9star** [comment]
登录后镜像不能切换，切换后需要重新登录。国内镜像不能开代理，国外镜像要开代理

**Comment by TingTing1990** [comment]
谢谢，请问这个"镜像"是哪里看？因为我没有做任何相关操作，我是24小时代理，从登录开始都是

**Comment by TingTing1990** [comment]
已经解决，把应用排除到代理走直连就正常了
