### ISSUE TITLE
能否在番剧简介中增加可以选择复制功能，或者点击超链打开

### ISSUE THREAD

**Issue by howrain** [iota9star/mikan_flutter#50]
有一些老番需要额外下载字幕等，无法在简介中复制链接有点麻烦

**Comment by iota9star** [comment]
没太明白，请详细描述一下

**Comment by howrain** [comment]
![微信图片_20231221155657](https://github.com/iota9star/mikan_flutter/assets/29175296/624725d3-94c9-48c9-ad1a-6f88ecd304f8)
![微信图片_20231221155703](https://github.com/iota9star/mikan_flutter/assets/29175296/8205b719-3d20-439d-8960-677b76fd7cb2)
一些老番的简介会有一些链接，但是目前界面无法复制，点击也打不开

**Comment by iota9star** [comment]
这个之前应该是好的，估计api修改了，我有空会发布修复版本

**Comment by howrain** [comment]
非常感谢！

**Comment by lycstar** [comment]
> > 这个之前应该是好的，估计api修改了，我有空会发布修复版本
> 
> 快一个月了佬，什么时候有空发呢？

v1.2.4已发布
