### ISSUE TITLE
期望集成下载功能

### ISSUE THREAD

**Issue by tsurumi-yizhou** [iota9star/mikan_flutter#51]
[DHT协议](https://justjavac.com/other/2015/02/01/bittorrent-dht-protocol.html)

**Comment by kechuan** [comment]
其实我觉得只要追加下载链接/下载torrent文件就好(我看网页官网实际上是有对应的接口的)
因为确实会存在连元数据都拖不下来的情况 反而直接给种子就能连上对应的tracker下载

我好多次在APP上磁力链接拖不下来 只能透过RSS订阅把种子拖下来。。
