### ISSUE TITLE
搜索结果页的RSS订阅链接中参数名有误

### ISSUE THREAD

**Issue by yburger** [iota9star/mikan_flutter#55]
软件中在搜索结果页点击RSS图标，自动复制的链接内容是：
`https://mikanani.me/RSS/Search?searcher=xxx`
此URL打开后并不包含搜索页的结果信息。
目前正确的RSS链接应是：
`https://mikanani.me/RSS/Search?searchstr=xxx`

**Comment by iota9star** [comment]
应该网页有调整，我处理一下
